truncate table llx_kjraffaire_dico_type_affaire; 
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Droit des sociétés',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Droit social',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Fusion absorption',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Fonds de commerce',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Fusion création',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Bail commercial (création)',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Contrat commerciaux',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Entreprise individiuelle',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Divorce par consentement individuel (nlle procédure)',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Divorce contentieux',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Bail commercial',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Divorce consentement mutuel',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Contrats commerciaux (ancien modèle)',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Bail habitation',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Abus de confiance',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Contrats civils',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Procédure',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Consultation',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Prospect',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Client RGPD',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Dossier client',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Action',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Action sociale',1);

truncate table llx_kjraffaire_dico_action_juridique;
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en justice au fond ("fonds")','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Référé expertise','Référé',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Référé provision','Référé',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Référé injonction','Référé',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Référé suspension','Référé',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Injonction de payer','Référé',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Injonction de faire','Référé',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en responsabilité civile','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en nullité','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en partage','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en révision','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Plainte avec constitution de partie civile','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Citation directe','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Recours pour excès de pouvoir','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Recours en responsabilité administrative','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en redressement judiciaire','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en liquidation judiciaire','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en concurrence déloyale','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en divorce','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en révision de pension alimentaire','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en modification de droit de garde','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en bornage','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en troubles du voisinage','Fonds',1);
insert into llx_kjraffaire_dico_action_juridique(label,typeaction,active) values('Action en résiliation de bail','Fonds',1);

