truncate table llx_kjraffaire_dico_type_affaire; 
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Droit des sociétés',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Droit social',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Fusion absorption',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Fonds de commerce',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Fusion création',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Bail commercial (création)',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Contrat commerciaux',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Entreprise individiuelle',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Divorce par consentement individuel (nlle procédure)',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Divorce contentieux',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Bail commercial',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Divorce consentement mutuel',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Contrats commerciaux (ancien modèle)',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Bail habitation',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Abus de confiance',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Contrats civils',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Procédure',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Consultation',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Prospect',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Client RGPD',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Dossier client',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Action',1);
insert into llx_kjraffaire_dico_type_affaire(label,active) values('Action sociale',1);